name: Daily YFinance Downloader

on:
  schedule:
    - cron: "0 2 * * *"  # Run every day at 2:00 UTC
  workflow_dispatch:     # Allow manual trigger

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # Max runtime: 6 hours

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Script
      run: |
        python main.py

    - name: Commit & Push Updated Parquet
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add parquet_data/
        git commit -m "Daily update"
        git push
      continue-on-error: true  # Avoid failure if nothing changed

