name: Daily Pipeline

on:
  schedule:
    - cron: "0 2 * * *"  # Run every day at 2:00 UTC
  workflow_dispatch:     # Allow manual trigger

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # Max runtime: 6 hours
    permissions:
      contents: write  # Critical for push access

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4.2.2

    - name: Set up Python
      uses: actions/setup-python@v5.6.0
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Downloads data from yfinance
      run: |
        python download.py

    - name: Commit & Push Updated Parquet
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add parquet_data/
        git commit -m "Daily update"
        git push

    - name: Consolidates the downloaded data
      run: |
        python consolidate.py

    - name: Generates metadata for the dataset
      run: |
        python metadata.py

    - name: Uploads the dataset to Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        python upload.py