name: Daily Pipeline Yahoo

on:
  schedule:
    - cron: "0 8 * * *"  # Run every day at 8:00 UTC
  workflow_dispatch:     # Allow manual trigger

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # Max runtime: 6 hours

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4.2.2

    - name: Set up Python
      uses: actions/setup-python@v5.6.0
      with:
        python-version: 3.13

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Sync data from yfinance
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        python main.py --source yahoo
